apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions: [ { key: app, operator: In, values: [ hello ] } ]
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: app
          image: kicbase/echo-server:latest
          ports:
            - name: http
              containerPort: 8080
      terminationGracePeriodSeconds: 1
