apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hi
  labels:
    app: hi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hi
  template:
    metadata:
      labels:
        app: hi
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: hi
          maxSkew: 1
#          nodeAffinityPolicy: Honor
#          nodeTaintsPolicy: Honor
          topologyKey: node-role.kubernetes.io
          whenUnsatisfiable: ScheduleAnyway #DoNotSchedule
#        - labelSelector:
#            matchLabels:
#              app: hi
#          maxSkew: 1
#          topologyKey: kubernetes.io/hostname
#          whenUnsatisfiable: DoNotSchedule
#          matchLabelKeys:
#            - pod-template-hash
      containers:
        - name: app
          image: kicbase/echo-server:latest
          ports:
            - name: http
              containerPort: 8080
      terminationGracePeriodSeconds: 1
  serviceName: hi
