apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hi
  labels:
    app: hi
spec:
  replicas: 30
  selector:
    matchLabels:
      app: hi
  template:
    metadata:
      labels:
        app: hi
    spec:
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: hi
          maxSkew: 1
#          nodeAffinityPolicy: Honor
#          nodeTaintsPolicy: Honor
          topologyKey: node-role.kubernetes.io
          whenUnsatisfiable: DoNotSchedule
        - labelSelector:
            matchLabels:
              app: hi
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
#          matchLabelKeys:
#            - pod-template-hash
      containers:
        - name: hi-from
          image: pbitty/hello-from:latest
          ports:
            - name: http
              containerPort: 80
      terminationGracePeriodSeconds: 1
  serviceName: hi
