apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hi2
  labels:
    app: hi2
spec:
  replicas: 30
  selector:
    matchLabels:
      app: hi2
  template:
    metadata:
      labels:
        app: hi2
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
#                    - key: app.kubernetes.io/instance
#                      operator: In
#                      values:
#                        - evs-tac
                    - key: app
                      operator: In
                      values:
                        - hi2
                topologyKey: node-role.kubernetes.io
#                topologyKey: topology.kubernetes.io/zone
#                topologyKey: kubernetes.io/hostname
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - hi2
                topologyKey: node.kubernetes.io/tst-wkr
              weight: 5
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: test/tst-wkr-rack1
#                operator: In
#                values:
#                - ""
      containers:
        - name: hi-from
          image: pbitty/hello-from:latest
          ports:
            - name: http
              containerPort: 80
      terminationGracePeriodSeconds: 1
  serviceName: hi2
