apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hi3
  labels:
    app: hi3
spec:
  replicas: 30
  selector:
    matchLabels:
      app: hi3
  template:
    metadata:
      labels:
        app: hi3
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: hi3
                topologyKey: node.kubernetes.io/tst-wkr
              weight: 5
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: hi3
          maxSkew: 1
          topologyKey: node-role.kubernetes.io
          whenUnsatisfiable: DoNotSchedule
      containers:
        - name: app
          image: kicbase/echo-server:latest
          ports:
            - name: http
              containerPort: 8080
      terminationGracePeriodSeconds: 1
  serviceName: hi3
