apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  properties-flink-jobmanager: |
    {{ include "{{ .Chart.Name }}.commonFlinkConfiguration" . }}
    jobmanager.memory.process.size: 2G
  properties-flink-taskmanager: |
    {{ include "{{ .Chart.Name }}.commonFlinkConfiguration" . }}
    taskmanager.memory.process.size: 2G
