apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        #
        - name: {{ .Chart.Name }}-jobmanager
          args: [ 'jobmanager' ]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: FLINK_PROPERTIES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: properties-flink-jobmanager
          livenessProbe:
            tcpSocket:
              port: 6123
            initialDelaySeconds: 300
            failureThreshold: 10
            periodSeconds: 120
          ports:
            - containerPort: 6123
              name: tcp-rpc
              protocol: TCP
            - containerPort: 6124
              name: tcp-blob
              protocol: TCP
            - containerPort: 8081
              name: http-ui
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 1500Mi
        #
        - name: {{ .Chart.Name }}-taskmanager
          args: [ 'taskmanager' ]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: FLINK_PROPERTIES
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}-configmap
                  key: properties-flink-taskmanager
          livenessProbe:
            tcpSocket:
              port: 6122
            initialDelaySeconds: 300
            failureThreshold: 10
            periodSeconds: 120
          ports:
            - containerPort: 6122
              name: tcp-rpc
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 400m
              memory: 1500Mi
