apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        #
        - name: {{ .Chart.Name }}-jobmanager
          command: [ '/docker-entrypoint.sh', 'jobmanager' ]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 6123
              name: tcp-rpc
              protocol: TCP
            - containerPort: 6124
              name: tcp-blob
              protocol: TCP
            - containerPort: 6125
              name: tcp-query
              protocol: TCP
            - containerPort: 8081
              name: http-ui
              protocol: TCP
        #
        - name: {{ .Chart.Name }}-taskmanager
          command: [ '/docker-entrypoint.sh', 'taskmanager' ]
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 6125
              name: tcp-query
              protocol: TCP
