apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-process
spec:
  selector:
    {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: rpc
      port: 6123
    - name: blob-server
      port: 6124
    - name: webui
      port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-rest
spec:
  selector:
    {{- include "{{ .Chart.Name }}.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports:
    - name: rest
      port: 8081
      targetPort: 8081
      nodePort: 30081
