apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 9000
